#ENC[AES256_GCM,data:EAosaBVG/gEjPBNKMBnDGBktO4VQJnN3cImA5ZSNVmoSpG3jRIQq5yojiJgDjLaRiCkvh4944XHofpNmTZjCPp1V9w==,iv:F6HK4sRC++IqMF8Yd5Kg0goTAHZQr801J9XS+zu41vw=,tag:jjMfQb4K/W6gLbc6cvUnJQ==,type:comment]
vault_discord_token: ENC[AES256_GCM,data:eLPxgl6LV5zSk+5DD40YvOB8Cy4LlDCjECB3wutvuBYTTy8Tlb2JTA63TahiinOiFbY+XeHCDXGfnAy17SrmCY8496Zy6EG6,iv:6FhaFsP+vQuu7tT9TBGZi1vwuHy3JxgaeDfNZUkj41s=,tag:IS546H/n8IlVGQxlUQcZBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qls3y5x9nymax25h9tes98huf8cwe923h95nyp03xduww64qmvnqht0x6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWHVBODBvM2R1YnJSYkNx
            U05mdzJlb204dUJQR3MrQ0VtcVNSci82RncwCjhYUnZ5QUM5Qk5HTTdLSzFhUTBq
            aWVCUkEwVEZvUHFkaGFKT3R2cGVrWlkKLS0tIGFzNm1YOUYyRTR5cldHS0lNUEo0
            azlnUmdvZ0U3UDFkVXZ1M0hlSHN5R0UKFmSIYOUEWJs343IKkxbBtdCoXJ1nZdBG
            Mh2VjD22on4a+Nb0Ojrgi2o/8vFXibzIALP0N7HxvoXJm5OmoyMiLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T23:21:44Z"
    mac: ENC[AES256_GCM,data:lvdp4OmLtSbM0BCUf4l+uyQ+Vomy33sOgzj0v3/rulqete1ewSoTT4Lwsh7ag4qG1vIubi8gSG+t0MwkUm87O3rJ8PyVoAreyOt/5ng/4HbFZXF1E9DOznZ4YF7SsDdwOlX+TxzyDB5Wgb+cjKoKEUvRd9+FtwsMgXvMg3M0WL0=,iv:IVJEXwvXO4vWx57w2iTamXHvFduDOeYsOzJFpW1Fd9g=,tag:g+4YOHAwifZIdinVFjee6A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
