#ENC[AES256_GCM,data:qVwwitKWCxltUmkRRc/msnkblHlayFMase09VVAwIxx9aqKQLegkBBK0UocpEA6otRrJcSZUpO+hFL6mJZ4lJzAEVvomdQ==,iv:AjP9b3e88pqw5RI4CRSuPlURM3QBZsFKDr5uLUngswU=,tag:rNOAf31cda7v+WB+ovrm/A==,type:comment]
vault_discord_token: ENC[AES256_GCM,data:5TBp3aX5bw6m1nNroU3SU+3gB0l0fSeaBmEVuXL+Pwco8+/ITmg=,iv:vi8soZiYw4KsSE23s6K0fsynuRBHRWL5pD0vPyU/v74=,tag:CUch8CpABs0x6236LfWbZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qls3y5x9nymax25h9tes98huf8cwe923h95nyp03xduww64qmvnqht0x6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOURLOUxURjJ1azQ1Q1hW
            NjBQcWdlWTJJeWF0TXEyZHdJeDJsUmtSOFI0Ck5EUmxkdVcwRXd5ZlY4eldWZDJa
            VXZWSDlzVENiUmw0UUV6ZVNrWGJyT0EKLS0tIFVmZWpwNmZPN0NmZERack4rMUJx
            SXVHcUJ1bU41Zmp5aTQ0ZVdiNEJ0Q0UKHUYlxcYBpBvgMviaG1BV5MZRqRrLSNNX
            BvgBS4gw124E/FNrZPQy5N9v0F0VzAjRfg535jUaFqQsCfOyoOEIWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T23:08:26Z"
    mac: ENC[AES256_GCM,data:yKvGuSwG58kfK9A/ckAOSbqs02R9U/OWI+Klbz+05o0kp0RoJEo104jtxa+Wt2Px5MTWhrDXIL5Ywykg3FUK0JKRmheCjrJhSd5fertC7Ycut5zhDkHOyLYJHyxER4VBoNkZZoF/rtSdWfwL6abWfwHNmU51+et65mA2rxr6PdA=,iv:HCIWi6fU+ofJcF0V6TEMrzVY70iDXsdn0Kgjhu+i9v4=,tag:w9+BPzmQAg9Vp+NyGa0MwA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
