#ENC[AES256_GCM,data:FhdHru32RZ8pwA0kwwP+EMtjaDd6aolp5tW/eVUxUaNDCLDu5ZWMuKUVlaXNiDZYWuY+qJi6iuejP9gU10bAOJFoSkoUZmLgsG8QDQ==,iv:sezZsQDBqJ8KW9PeItt3wRT9qdxV2mEceS+/Vix/YdM=,tag:4s+N1GMTxh3RhrrTJv1CAQ==,type:comment]
vault_pihole_password: ENC[AES256_GCM,data:VyABmseNLHiUhYAyFFQ+ocr94Ge39mr7,iv:WRsmVQ23HHRHKt9Vl8QaMtXetJ3C1AiJCZ/kLhYfc68=,tag:l0/ZEMZyAHzwhHxo7GtBBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qls3y5x9nymax25h9tes98huf8cwe923h95nyp03xduww64qmvnqht0x6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM0Jubjh0RjBvVmlCempX
            WnJhVjRKNitEOUIxT1VCZktiL3hGam10L21RCmMrTFIycEk1YWxxVHAyYXR1VFlx
            dEYyZkx4bkNlOHNzRGdpbWpIYnQxa00KLS0tIEN3YXRCaW9tTk1GM2FBL05DTWg5
            RGFYNHlXK0I2MkhHR1NZbnluaXZ6Rm8KZ4kb5zqjo4RJzRdEAK2zERnMxbPrGd89
            Czqo6gVYNMSzDtdZZCtElTwHHGk4jO2UxV9CvdbhNZERnyXZPTV5qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T19:17:04Z"
    mac: ENC[AES256_GCM,data:aDdL32mCidKaV58fR2BXd+KTXjRFfjb2nWy9h54KIguIsxg+RAKq6MDUzF8iBmcdKF0OcxwcOpAX8MoXgFoxkDLTHsu5pUET5tQrCD9qJH4quMZvjy3x3AAtIe2Eashf1aKS7xVKlyOz/Ft1IJ1uLqiB/s99ptQsM9kYMa63NQE=,iv:YJlJWcbzIObpdzVTLUznAhUyYIGNJ1wnAWUYRmBFiqY=,tag:rIlGPHiUBi+MtZZaNKa0yA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
